language: ruby
cache: bundler
rvm:
- 2.1.0

env:
  global:
    secure: fnib8LioCdh1IzrnesdAewd4LutkHAQ0+shbWjSXEd4yKhEJWyjMgy/44EGA1gUofFI8ZWRoom6jX1dULv7+MDQiLBxQTogxQc9BE92c69hTDCul2EVB108M3YNxTejSzKUb15oXbKxAaHVNuUVV+2xfv1AD6UYJYFkvThiXBjA=

before_script: bundle exec rake site:stage
script: bundle exec rake site:build
after_success: bundle exec rake site:deploy
