# Configuration
kramdown:
  input: GFM

permalink: pretty
relative_permalinks: false

gems:
  - jekyll-sitemap
  - jekyll-redirect-from

sass:
  style: :compressed
  sass_dir: _assets/css

remote_data:
  github_owner:   https://api.github.com/orgs/absolute413
  photos:         https://graph.facebook.com/606796236030457/photos?fields=name,source,picture,updated_time&limit=100
  special_photos: https://graph.facebook.com/733929783317101/photos?fields=name,source,picture,updated_time&limit=100

exclude:
  - README
  - LICENSE
  - vendor
  - Gemfile
  - Rakefile

notifications:
  email:
    on_success: never
    on_failure: change


# Metadata
url: #http://pizzaacademy.com
baseurl: /PizzaAcademy-Preview

title: Pizza Academy
tagline: Subs, Salads & Roast Beef
description: Open 7 days a week, and we deliver all day.
