# Configuration
safe: true

kramdown:
  input: GFM

permalink: pretty
relative_permalinks: false

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-github-metadata

whitelist:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-github-metadata

sass:
  style: :compressed

exclude:
  - README
  - Gemfile
  - vendor

# Metadata
baseurl: ""
excerpt_separator: ""

logo: /assets/img/open-graph.jpg
title: Pizza Academy
tagline: Subs, Salads & Roast Beef
description: Open 7 days a week, and we deliver all day.

# Plugins
repository: MadeByGlutard/PizzaAcademy.com # Populate site.github locally

compress_html:
  clippings: all
  comments: all
  endings: all
  ignore: { envs: [ local ] }

defaults:
  - scope:
      path: ""
    values:
      image: /assets/img/open-graph.jpg

collections:
  assets:
    output: true
  public:
    output: true
    permalink: /:path
