backend:
  name: git-gateway
  branch: master

media_folder: static/images
public_folder: /images

collections:
- name: settings
  label: Settings
  editor:
    preview: false
  files:
  - name: hours
    label: Hours
    file: content/hours.yaml
    fields:
    - name: hours
      label: Hours
      widget: list
      fields:
      - name: days
        label: Days
        widget: string
      - name: time
        label: Time
        widget: list

  - name: menu
    label: Menu
    file: content/menu.yaml
    fields:
    - name: menu
      label: Menu
      widget: list
      fields:
      - name: name
        label: Name
        widget: string
      - name: details
        label: Details
        widget: list
      - name: toppings
        label: Toppings
        widget: list
      - name: sizes
        label: Sizes
        widget: list
      - name: items
        label: Items
        widget: list
        fields:
        - name: name
          label: Name
          widget: string
        - name: description
          label: Description
          widget: string
        - name: prices
          label: Prices
          widget: list
      - name: extras
        label: Extras
        widget: list
        fields:
        - name: name
          label: Name
          widget: string
        - name: prices
          label: Prices
          widget: list

  - name: specials
    label: Specials
    file: content/specials.yaml
    fields:
    - name: specials
      label: Specials
      widget: list
      fields:
      - name: name
        label: Name
        widget: string
      - name: detail
        label: Detail
        widget: string
      - name: price
        label: Price
        widget: string

  - name: flavors
    label: Flavors
    file: content/flavors.yaml
    fields:
    - name: flavors
      label: Flavors
      widget: list
      fields:
      - name: name
        label: Name
        widget: string
